name: restory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^8.0.6
  syncfusion_flutter_pdf: ^28.1.33
  path_provider: ^2.1.3
  share_plus: ^10.0.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/H.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
